# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

argument_specs:
  main:
    short_description: "Create a set of Tool Templates"
    description:
      - Configure a specified list of Tool Templates with Cloudera AI Studios.
    author:
      - "Jim Enright <jenright@cloudera.com>"
    options:
      cai_workspace_api:
        description:
          - Cloudera AI Workbench API endpoint
        type: str
        required: true
      cai_workbench_api_key:
        description:
          - Cloudera AI Workbench API v2 key
        type: str
        required: true
      cai_project:
        description: 
          - The name of a pre-existing Cloudera AI project name.
        type: str
        required: true
      cai_user:
        description: 
          - Cloudera AI Username.
          - Usually your workload username.
        type: str
        required: true
      ai_studio:
        description:
          - String to select pre-defined AI Studio configurations
          - Setting O(cai_ai_studio_details) variable ignores this variable
        type: str
        default: "agent_studio"
        choices:
          - agent_studio
          - fine_tuning_studio
          - synthetic_data_studio
          - rag_studio
      cai_ai_studio_details:
        description:
          - String to select pre-defined AI Studio configurations
          - Setting O(cai_ai_studio_details) variable ignores this variable
        type: dict
        required: false
        options:
          slug:
            type: str
            description: Slug for deployed AI Studio application
          application_name:
            type: str
            description: Display name of the AI Studio
      tool_templates:
        description:
          - List of Tool Templates to create
        type: list
        elements: dict
        required: false
        default: []
        suboptions:
          template_name:
            type: str
            description: Name of the Tool Template to create
          file:
            type: str
            description: Location of the source code for the Tool Templat
          tool_image_path:
            type: str
            description: Path to an icon image for the Tool Template (optional)
          workflow_template_id:
            type: str
            description: ID of the workflow template to use (optional)
