site_name: "Cloudera AI Agentic Studio Hands on Lab"
site_author: GOES
copyright: 2025 Cloudera, Inc. All rights reserved.<br><a href="https://www.cloudera.com/legal/terms-and-conditions.html" target="_blank">Terms & Conditions | </a>  <a href="https://www.cloudera.com/legal/policies.html" target="_blank"> Privacy Policy and Data Policy</a>
repo_url: https://github.infra.cloudera.com/GOES/hol-005-agentic-studio
repo_name: goes/hol-005-agentic-studio
theme:
    name: material
    logo: assets/images/logo-cloudera-white.svg
    favicon: assets/images/favicon.ico
    palette:
    - scheme: default
      primary: #FFFFFF
      accent: #121212
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - content.code.annotate
    - content.code.copy
    # - navigation.expand
    # - navigation.indexes
    # - navigation.sections
    - navigation.footer    
    - navigation.top

docs_dir: '../../content'
site_dir: './build'
# not_in_nav: |
extra_css:
  - assets/stylesheets/extra.css
use_directory_urls: false
extra:
  generator: false

nav:
  - Home: 'README.md'
  - Modules:
    - Workshop Scope: 'modules/README.md'
    - Module 1 - Hand code AI Agents:
      - Overview: 'modules/module1/README.md'
      - Lab 1 - Getting Setup for Workshop: 'modules/module1/lab1.md'
      - Lab 2 - Building Your First AI Agent: 'modules/module1/lab2.md'
      - Lab 3 - Custom Tools in Agentic Workflow: 'modules/module1/lab3.md'
    - Module 2 - Designing Multi Agent Workflow On Agent Studio:
      - Overview: 'modules/module2/README.md'
      - Lab 1 - Create Templates and workflows in Agent Studio: 'modules/module2/lab1.md'
      - Lab 2 - Create Tasks in Agent Studio: 'modules/module2/lab2.md'
      - Lab 3 - Create Custom Tools in Agent Studio: 'modules/module2/lab3.md'
      - Lab 4 - Test, Monitor and Deploy Workflows: 'modules/module2/lab4.md'

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.tasklist:
      custom_checkbox: true  
  - sane_lists: {}
  - toc:
      toc_depth: 3

plugins:
  - same-dir # to allow site_dir to be within docs_dir
  - search
  - markdownextradata: {}
  # - with-pdf:
  #     custom_template_path: templates
  #     debug_html: false
  #     output_path: exercise_guide.pdf
  - glightbox